// Objective-C API for talking to bitbucket.org/avcl/testinggomobile Go package.
//   gobind -lang=objc -prefix=Go bitbucket.org/avcl/testinggomobile
//
// File is generated by gobind. Do not edit.

#ifndef __GoTest_H__
#define __GoTest_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

FOUNDATION_EXPORT BOOL GoTestHello(NSError** error);

#endif
