
// Objective-C API for talking to the following Go packages
//
//	bitbucket.org/avcl/testinggomobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Test_H__
#define __Test_H__

#include "GoTest.h"
#include "GoUniverse.h"

#endif
